In [9]:
import numpy as np
arr_a = np.arange(10,51,10)
arr_b = np.arange(0, 101, 5)
arr_c = np.full([4,3], 7.5)
print(arr_c)

[[7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]]


In [19]:
set1_a = np.full([2,5], 0)
set1_b = np.multiply(np.ones([3,3],dtype=np.int16),3)
set1_c = np.linspace(1,5,15)
set1_c_reshaped = set1_c.reshape(5,3)
a = np.full([2,2], 5)
b = np.full([2,2], 3)
a_plus_b = np.add(a,b)

In [49]:
set2_a = np.arange(1, 26, 2)
set2_b = np.full([2, 4,], 4.0, dtype=np.float32)
print(set2_b.shape, set2_b.dtype)
set2_b_reshaped = set2_b.reshape(1,8)
set2_b_transposed = np.transpose(set2_b)
M = np.array([(1,2), (3,4)])
M = np.multiply(M, 10)

(2, 4) float32


In [37]:
set3_a = np.linspace(0, 1, 10)
set3_a_int32 = np.int32(np.linspace(0, 1, 10))
print(set3_a_int32)
np.empty((5,2))

[0 0 0 0 0 0 0 0 0 1]


array([[0.        , 0.11111111],
       [0.22222222, 0.33333333],
       [0.44444444, 0.55555556],
       [0.66666667, 0.77777778],
       [0.88888889, 1.        ]])

In [38]:
m1 = np.full([2,3], 6.0)
m1_multiplied = np.multiply(m1, 2.5)
print(m1_multiplied)

[[15. 15. 15.]
 [15. 15. 15.]]


In [55]:
set3_c = np.arange(1,11, 1)
measured_set3_c = (set3_c > 4) & (set3_c < 8)
print(set3_c[(set3_c > 4) & (set3_c < 8)])

[5 6 7]


In [57]:
v1 = np.arange(1, 5)
v2 = np.arange(5, 9)
el_wise_mult = np.multiply(v1, v2)
print(el_wise_mult)

[ 5 12 21 32]
